name: test_docs_build
on:
  # Trigger on pull requests against the master branch
  pull_request:
    branches:
      - master
jobs:
  test_docs_build:
    runs-on: ubuntu-latest
    strategy:
      # Spawn and run a job for each of two supported Python 3.x versions
      matrix:
        python: [3.7, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up a version of Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip and install Tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Run tests using Tox
        run: tox -e py
